[package]
name = "rstow"
version = "1.0.1"
authors = ["qboileau <quentin.boileau@gmail.com>"]

[dependencies]
quicli = "0.4.0"
im = "15.1.0"
failure = "0.1.2"
failure_derive = "0.1.2"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5.3"
structopt = "0.3.26"
log = "0.4.17"
